name: "Code review"

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: StandardRB Linter
      uses: andrewmcodes/standardrb-action@v0.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    - run: bundle install
    - run: bundle exec rspec